export const SET_ONBOARDING_SUCCESS = "SET_ONBOARDING_SUCCESS"
export const SET_ONBOARDING_ERROR = "SET_ONBOARDING_ERROR"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR"